version: "2"
services:
    angular:
        image: wave-angular
        build:
            context: "./angular"
            dockerfile: "docker/Dockerfile"
        ports:
         - "3000:3000"
        networks:
           wave:
               aliases:
                   - wave-angular
        volumes:
         - "./angular:/src/"
        container_name: wave-angular
    api:
        image: wave-api
        build:
            context: ./api/
            dockerfile: docker/Dockerfile
        networks: 
            wave:
                aliases:
                    - wave-api
        volumes:
            - "./api/:/src/"
        ports:
            - "8000:8000"
        container_name: wave-api
        depends_on:
            - mysql
    mysql:
        image: wave-mysql
        build:
            context: ./mysql/
            dockerfile: docker/Dockerfile
        networks: 
            wave:
                aliases:
                    - wave-mysql
        volumes:
            - "./mysql/:/src/"
            - "./data/:/var/lib/mysql"
        container_name: wave-mysql
networks:
    wave: